name: Pre-release

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_prerelease:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app-service/requirements.txt ]; then
            pip install -r app-service/requirements.txt
          else
            echo "Warning: app-service/requirements.txt not found. Skipping pip install."
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "triggered_by=tag" >> $GITHUB_OUTPUT
          else
            echo "triggered_by=branch" >> $GITHUB_OUTPUT
          fi

      - name: Get latest tag from history
        if: steps.trigger.outputs.triggered_by == 'branch'
        run: |
          LATEST=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST" >> $GITHUB_ENV

      - name: Get latest tag from pushed tag
        if: steps.trigger.outputs.triggered_by == 'tag'
        run: |
          echo "LATEST_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Calculate pre-release version
        run: |
          # strip leading 'v' and any '-pre' suffix
          BASE=${LATEST_TAG#v}
          BASE=${BASE%%-pre*}
          IFS=. read MAJOR MINOR PATCH <<< "$BASE"

          # always bump patch for prerelease
          PATCH=$((PATCH + 1))
          TS=$(date +%Y%m%d.%H%M%S)
          PRERELEASE="$MAJOR.$MINOR.$PATCH-pre.$TS"

          echo "version=$PRERELEASE"        >> $GITHUB_ENV
          echo "version_major=$MAJOR"       >> $GITHUB_ENV
          echo "version_minor=$MINOR"       >> $GITHUB_ENV
          echo "version_patch=$PATCH"       >> $GITHUB_ENV

      - name: Tag pre-release commit
        if: steps.trigger.outputs.triggered_by == 'branch'
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          SHA=$(git rev-parse origin/main)
          git tag "v${{ env.version }}" $SHA
          git push origin "v${{ env.version }}"

      - name: Build and push Docker image (multi-arch)
        run: |
          REPO=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          IMG="ghcr.io/${REPO}/${NAME}"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -t "${IMG}:v${{ env.version }}" \
            -t "${IMG}:${{ env.version_major }}.${{ env.version_minor }}.latest" \
            -t "${IMG}:${{ env.version_major }}.latest" \
            -t "${IMG}:latest" \
            --push .

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.version }}"
          name: Pre-release v${{ env.version }}
          body: |
            Automated **pre-release** for version **v${{ env.version }}**.

            • Multi-arch Docker images pushed to `ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}`  
            • Tagged: `v${{ env.version }}`, `${{ env.version_major }}.${{ env.version_minor }}.latest`, `${{ env.version_major }}.latest`, `latest`
          draft: false
          prerelease: true
